var mongoose = require('mongoose'),
    UserSchema = new mongoose.Schema({
        username: {type: String, index: {unique: true, dropDups: true}},
        urlname: {type: String, index: {unique: true, dropDups: true}},
        password: String,
        email: {type: String, index: {unique: true, dropDups: true}},
        activated: {type: Boolean, default: true},
        banned: Boolean,
        ban_reason: String,
        last_ip: String,
        last_login: Date,
        created: Date,
        modified: Date,
        view_html: {type: Boolean, default: true},
        random_titles: {type: Boolean, default: true},
        timezone: {type: Number, default: 0},
        emoticon: String,
        custom_css: String,
        threads_count: {type: Number, default: 0},
        comments_count: {type: Number, default: 0},
        hide_enemy_posts: Boolean,
        custom_js: String,
        hide_ads: Boolean,
        points: {type: Number, default: 0, min: 0},
        lastpointusage: Date,
        thread_size: {type: Number, default: 50},
        comment_size: {type: Number, default: 50},
        participated: [String],
        favourites: [String],
        hidden: [String]
    });

module.exports = UserSchema;